// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/cache.dart';
import 'api/download.dart';
import 'api/init.dart';
import 'api/models.dart';
import 'api/search.dart';
import 'api/settings.dart';
import 'api/simple.dart';
import 'api/user.dart';
import 'api/video.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<ApiDownloadTask> dco_decode_StreamSink_api_download_task_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<ApiExportProgress>
  dco_decode_StreamSink_api_export_progress_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ApiAppSettings dco_decode_api_app_settings(dynamic raw);

  @protected
  ApiAuthorInfo dco_decode_api_author_info(dynamic raw);

  @protected
  ApiBanner dco_decode_api_banner(dynamic raw);

  @protected
  ApiCloudflareChallenge dco_decode_api_cloudflare_challenge(dynamic raw);

  @protected
  ApiComment dco_decode_api_comment(dynamic raw);

  @protected
  ApiCommentList dco_decode_api_comment_list(dynamic raw);

  @protected
  ApiDownloadStatus dco_decode_api_download_status(dynamic raw);

  @protected
  ApiDownloadTask dco_decode_api_download_task(dynamic raw);

  @protected
  ApiExportProgress dco_decode_api_export_progress(dynamic raw);

  @protected
  ApiFavoriteList dco_decode_api_favorite_list(dynamic raw);

  @protected
  ApiFilterOption dco_decode_api_filter_option(dynamic raw);

  @protected
  ApiFilterOptions dco_decode_api_filter_options(dynamic raw);

  @protected
  ApiHomePage dco_decode_api_home_page(dynamic raw);

  @protected
  ApiHomeSection dco_decode_api_home_section(dynamic raw);

  @protected
  ApiMyListInfo dco_decode_api_my_list_info(dynamic raw);

  @protected
  ApiMyListItem dco_decode_api_my_list_item(dynamic raw);

  @protected
  ApiPlayHistory dco_decode_api_play_history(dynamic raw);

  @protected
  ApiPlayHistoryList dco_decode_api_play_history_list(dynamic raw);

  @protected
  ApiPlaylistInfo dco_decode_api_playlist_info(dynamic raw);

  @protected
  ApiSearchFilters dco_decode_api_search_filters(dynamic raw);

  @protected
  ApiSearchResult dco_decode_api_search_result(dynamic raw);

  @protected
  ApiSeriesInfo dco_decode_api_series_info(dynamic raw);

  @protected
  ApiSeriesVideo dco_decode_api_series_video(dynamic raw);

  @protected
  ApiSubscriptionsPage dco_decode_api_subscriptions_page(dynamic raw);

  @protected
  ApiTagGroup dco_decode_api_tag_group(dynamic raw);

  @protected
  ApiUserInfo dco_decode_api_user_info(dynamic raw);

  @protected
  ApiVideoCard dco_decode_api_video_card(dynamic raw);

  @protected
  ApiVideoDetail dco_decode_api_video_detail(dynamic raw);

  @protected
  ApiVideoQuality dco_decode_api_video_quality(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ApiAppSettings dco_decode_box_autoadd_api_app_settings(dynamic raw);

  @protected
  ApiAuthorInfo dco_decode_box_autoadd_api_author_info(dynamic raw);

  @protected
  ApiBanner dco_decode_box_autoadd_api_banner(dynamic raw);

  @protected
  ApiCloudflareChallenge dco_decode_box_autoadd_api_cloudflare_challenge(
    dynamic raw,
  );

  @protected
  ApiMyListInfo dco_decode_box_autoadd_api_my_list_info(dynamic raw);

  @protected
  ApiPlayHistory dco_decode_box_autoadd_api_play_history(dynamic raw);

  @protected
  ApiPlaylistInfo dco_decode_box_autoadd_api_playlist_info(dynamic raw);

  @protected
  ApiSearchFilters dco_decode_box_autoadd_api_search_filters(dynamic raw);

  @protected
  ApiSeriesInfo dco_decode_box_autoadd_api_series_info(dynamic raw);

  @protected
  ApiUserInfo dco_decode_box_autoadd_api_user_info(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  CacheInfo dco_decode_cache_info(dynamic raw);

  @protected
  CacheSize dco_decode_cache_size(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ApiAuthorInfo> dco_decode_list_api_author_info(dynamic raw);

  @protected
  List<ApiComment> dco_decode_list_api_comment(dynamic raw);

  @protected
  List<ApiDownloadTask> dco_decode_list_api_download_task(dynamic raw);

  @protected
  List<ApiFilterOption> dco_decode_list_api_filter_option(dynamic raw);

  @protected
  List<ApiHomeSection> dco_decode_list_api_home_section(dynamic raw);

  @protected
  List<ApiMyListItem> dco_decode_list_api_my_list_item(dynamic raw);

  @protected
  List<ApiPlayHistory> dco_decode_list_api_play_history(dynamic raw);

  @protected
  List<ApiSeriesVideo> dco_decode_list_api_series_video(dynamic raw);

  @protected
  List<ApiTagGroup> dco_decode_list_api_tag_group(dynamic raw);

  @protected
  List<ApiVideoCard> dco_decode_list_api_video_card(dynamic raw);

  @protected
  List<ApiVideoQuality> dco_decode_list_api_video_quality(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ApiAuthorInfo? dco_decode_opt_box_autoadd_api_author_info(dynamic raw);

  @protected
  ApiBanner? dco_decode_opt_box_autoadd_api_banner(dynamic raw);

  @protected
  ApiCloudflareChallenge? dco_decode_opt_box_autoadd_api_cloudflare_challenge(
    dynamic raw,
  );

  @protected
  ApiMyListInfo? dco_decode_opt_box_autoadd_api_my_list_info(dynamic raw);

  @protected
  ApiPlayHistory? dco_decode_opt_box_autoadd_api_play_history(dynamic raw);

  @protected
  ApiPlaylistInfo? dco_decode_opt_box_autoadd_api_playlist_info(dynamic raw);

  @protected
  ApiSeriesInfo? dco_decode_opt_box_autoadd_api_series_info(dynamic raw);

  @protected
  ApiUserInfo? dco_decode_opt_box_autoadd_api_user_info(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<ApiDownloadTask> sse_decode_StreamSink_api_download_task_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ApiExportProgress>
  sse_decode_StreamSink_api_export_progress_Sse(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ApiAppSettings sse_decode_api_app_settings(SseDeserializer deserializer);

  @protected
  ApiAuthorInfo sse_decode_api_author_info(SseDeserializer deserializer);

  @protected
  ApiBanner sse_decode_api_banner(SseDeserializer deserializer);

  @protected
  ApiCloudflareChallenge sse_decode_api_cloudflare_challenge(
    SseDeserializer deserializer,
  );

  @protected
  ApiComment sse_decode_api_comment(SseDeserializer deserializer);

  @protected
  ApiCommentList sse_decode_api_comment_list(SseDeserializer deserializer);

  @protected
  ApiDownloadStatus sse_decode_api_download_status(
    SseDeserializer deserializer,
  );

  @protected
  ApiDownloadTask sse_decode_api_download_task(SseDeserializer deserializer);

  @protected
  ApiExportProgress sse_decode_api_export_progress(
    SseDeserializer deserializer,
  );

  @protected
  ApiFavoriteList sse_decode_api_favorite_list(SseDeserializer deserializer);

  @protected
  ApiFilterOption sse_decode_api_filter_option(SseDeserializer deserializer);

  @protected
  ApiFilterOptions sse_decode_api_filter_options(SseDeserializer deserializer);

  @protected
  ApiHomePage sse_decode_api_home_page(SseDeserializer deserializer);

  @protected
  ApiHomeSection sse_decode_api_home_section(SseDeserializer deserializer);

  @protected
  ApiMyListInfo sse_decode_api_my_list_info(SseDeserializer deserializer);

  @protected
  ApiMyListItem sse_decode_api_my_list_item(SseDeserializer deserializer);

  @protected
  ApiPlayHistory sse_decode_api_play_history(SseDeserializer deserializer);

  @protected
  ApiPlayHistoryList sse_decode_api_play_history_list(
    SseDeserializer deserializer,
  );

  @protected
  ApiPlaylistInfo sse_decode_api_playlist_info(SseDeserializer deserializer);

  @protected
  ApiSearchFilters sse_decode_api_search_filters(SseDeserializer deserializer);

  @protected
  ApiSearchResult sse_decode_api_search_result(SseDeserializer deserializer);

  @protected
  ApiSeriesInfo sse_decode_api_series_info(SseDeserializer deserializer);

  @protected
  ApiSeriesVideo sse_decode_api_series_video(SseDeserializer deserializer);

  @protected
  ApiSubscriptionsPage sse_decode_api_subscriptions_page(
    SseDeserializer deserializer,
  );

  @protected
  ApiTagGroup sse_decode_api_tag_group(SseDeserializer deserializer);

  @protected
  ApiUserInfo sse_decode_api_user_info(SseDeserializer deserializer);

  @protected
  ApiVideoCard sse_decode_api_video_card(SseDeserializer deserializer);

  @protected
  ApiVideoDetail sse_decode_api_video_detail(SseDeserializer deserializer);

  @protected
  ApiVideoQuality sse_decode_api_video_quality(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ApiAppSettings sse_decode_box_autoadd_api_app_settings(
    SseDeserializer deserializer,
  );

  @protected
  ApiAuthorInfo sse_decode_box_autoadd_api_author_info(
    SseDeserializer deserializer,
  );

  @protected
  ApiBanner sse_decode_box_autoadd_api_banner(SseDeserializer deserializer);

  @protected
  ApiCloudflareChallenge sse_decode_box_autoadd_api_cloudflare_challenge(
    SseDeserializer deserializer,
  );

  @protected
  ApiMyListInfo sse_decode_box_autoadd_api_my_list_info(
    SseDeserializer deserializer,
  );

  @protected
  ApiPlayHistory sse_decode_box_autoadd_api_play_history(
    SseDeserializer deserializer,
  );

  @protected
  ApiPlaylistInfo sse_decode_box_autoadd_api_playlist_info(
    SseDeserializer deserializer,
  );

  @protected
  ApiSearchFilters sse_decode_box_autoadd_api_search_filters(
    SseDeserializer deserializer,
  );

  @protected
  ApiSeriesInfo sse_decode_box_autoadd_api_series_info(
    SseDeserializer deserializer,
  );

  @protected
  ApiUserInfo sse_decode_box_autoadd_api_user_info(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  CacheInfo sse_decode_cache_info(SseDeserializer deserializer);

  @protected
  CacheSize sse_decode_cache_size(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ApiAuthorInfo> sse_decode_list_api_author_info(
    SseDeserializer deserializer,
  );

  @protected
  List<ApiComment> sse_decode_list_api_comment(SseDeserializer deserializer);

  @protected
  List<ApiDownloadTask> sse_decode_list_api_download_task(
    SseDeserializer deserializer,
  );

  @protected
  List<ApiFilterOption> sse_decode_list_api_filter_option(
    SseDeserializer deserializer,
  );

  @protected
  List<ApiHomeSection> sse_decode_list_api_home_section(
    SseDeserializer deserializer,
  );

  @protected
  List<ApiMyListItem> sse_decode_list_api_my_list_item(
    SseDeserializer deserializer,
  );

  @protected
  List<ApiPlayHistory> sse_decode_list_api_play_history(
    SseDeserializer deserializer,
  );

  @protected
  List<ApiSeriesVideo> sse_decode_list_api_series_video(
    SseDeserializer deserializer,
  );

  @protected
  List<ApiTagGroup> sse_decode_list_api_tag_group(SseDeserializer deserializer);

  @protected
  List<ApiVideoCard> sse_decode_list_api_video_card(
    SseDeserializer deserializer,
  );

  @protected
  List<ApiVideoQuality> sse_decode_list_api_video_quality(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ApiAuthorInfo? sse_decode_opt_box_autoadd_api_author_info(
    SseDeserializer deserializer,
  );

  @protected
  ApiBanner? sse_decode_opt_box_autoadd_api_banner(
    SseDeserializer deserializer,
  );

  @protected
  ApiCloudflareChallenge? sse_decode_opt_box_autoadd_api_cloudflare_challenge(
    SseDeserializer deserializer,
  );

  @protected
  ApiMyListInfo? sse_decode_opt_box_autoadd_api_my_list_info(
    SseDeserializer deserializer,
  );

  @protected
  ApiPlayHistory? sse_decode_opt_box_autoadd_api_play_history(
    SseDeserializer deserializer,
  );

  @protected
  ApiPlaylistInfo? sse_decode_opt_box_autoadd_api_playlist_info(
    SseDeserializer deserializer,
  );

  @protected
  ApiSeriesInfo? sse_decode_opt_box_autoadd_api_series_info(
    SseDeserializer deserializer,
  );

  @protected
  ApiUserInfo? sse_decode_opt_box_autoadd_api_user_info(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_api_download_task_Sse(
    RustStreamSink<ApiDownloadTask> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_api_export_progress_Sse(
    RustStreamSink<ApiExportProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_api_app_settings(
    ApiAppSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_author_info(ApiAuthorInfo self, SseSerializer serializer);

  @protected
  void sse_encode_api_banner(ApiBanner self, SseSerializer serializer);

  @protected
  void sse_encode_api_cloudflare_challenge(
    ApiCloudflareChallenge self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_comment(ApiComment self, SseSerializer serializer);

  @protected
  void sse_encode_api_comment_list(
    ApiCommentList self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_download_status(
    ApiDownloadStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_download_task(
    ApiDownloadTask self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_export_progress(
    ApiExportProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_favorite_list(
    ApiFavoriteList self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_filter_option(
    ApiFilterOption self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_filter_options(
    ApiFilterOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_home_page(ApiHomePage self, SseSerializer serializer);

  @protected
  void sse_encode_api_home_section(
    ApiHomeSection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_my_list_info(
    ApiMyListInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_my_list_item(
    ApiMyListItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_play_history(
    ApiPlayHistory self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_play_history_list(
    ApiPlayHistoryList self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_playlist_info(
    ApiPlaylistInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_search_filters(
    ApiSearchFilters self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_search_result(
    ApiSearchResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_series_info(ApiSeriesInfo self, SseSerializer serializer);

  @protected
  void sse_encode_api_series_video(
    ApiSeriesVideo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_subscriptions_page(
    ApiSubscriptionsPage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_tag_group(ApiTagGroup self, SseSerializer serializer);

  @protected
  void sse_encode_api_user_info(ApiUserInfo self, SseSerializer serializer);

  @protected
  void sse_encode_api_video_card(ApiVideoCard self, SseSerializer serializer);

  @protected
  void sse_encode_api_video_detail(
    ApiVideoDetail self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_video_quality(
    ApiVideoQuality self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_api_app_settings(
    ApiAppSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_api_author_info(
    ApiAuthorInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_api_banner(
    ApiBanner self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_api_cloudflare_challenge(
    ApiCloudflareChallenge self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_api_my_list_info(
    ApiMyListInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_api_play_history(
    ApiPlayHistory self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_api_playlist_info(
    ApiPlaylistInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_api_search_filters(
    ApiSearchFilters self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_api_series_info(
    ApiSeriesInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_api_user_info(
    ApiUserInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_cache_info(CacheInfo self, SseSerializer serializer);

  @protected
  void sse_encode_cache_size(CacheSize self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_api_author_info(
    List<ApiAuthorInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_comment(
    List<ApiComment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_download_task(
    List<ApiDownloadTask> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_filter_option(
    List<ApiFilterOption> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_home_section(
    List<ApiHomeSection> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_my_list_item(
    List<ApiMyListItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_play_history(
    List<ApiPlayHistory> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_series_video(
    List<ApiSeriesVideo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_tag_group(
    List<ApiTagGroup> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_video_card(
    List<ApiVideoCard> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_video_quality(
    List<ApiVideoQuality> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_api_author_info(
    ApiAuthorInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_api_banner(
    ApiBanner? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_api_cloudflare_challenge(
    ApiCloudflareChallenge? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_api_my_list_info(
    ApiMyListInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_api_play_history(
    ApiPlayHistory? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_api_playlist_info(
    ApiPlaylistInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_api_series_info(
    ApiSeriesInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_api_user_info(
    ApiUserInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
