// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 自动清理缓存（启动时调用）
/// - web_expire_ms: Web 缓存过期时间（毫秒），默认 10 分钟
/// - image_expire_ms: 图片缓存过期时间（毫秒），默认 3 天
Future<void> autoCleanCache({
  PlatformInt64? webExpireMs,
  PlatformInt64? imageExpireMs,
}) => RustLib.instance.api.crateApiCacheAutoCleanCache(
  webExpireMs: webExpireMs,
  imageExpireMs: imageExpireMs,
);

/// 清理所有缓存
Future<void> clearAllCache() =>
    RustLib.instance.api.crateApiCacheClearAllCache();

/// 仅清理图片缓存
Future<void> clearImageCache() =>
    RustLib.instance.api.crateApiCacheClearImageCache();

/// 仅清理 Web 缓存
Future<void> clearWebCache() =>
    RustLib.instance.api.crateApiCacheClearWebCache();

/// 获取缓存大小信息
Future<CacheSize> getCacheSize() =>
    RustLib.instance.api.crateApiCacheGetCacheSize();

/// 加载缓存图片（如果不存在则下载）
/// 返回本地文件路径
Future<String> loadCachedImage({required String url}) =>
    RustLib.instance.api.crateApiCacheLoadCachedImage(url: url);

/// VACUUM 数据库
Future<void> vacuumDatabase() =>
    RustLib.instance.api.crateApiCacheVacuumDatabase();

/// 缓存大小信息
class CacheSize {
  /// 图片缓存大小（字节）
  final BigInt imageCacheBytes;

  /// 图片缓存文件数量
  final BigInt imageCacheCount;

  /// Web 缓存条目数量
  final BigInt webCacheCount;

  const CacheSize({
    required this.imageCacheBytes,
    required this.imageCacheCount,
    required this.webCacheCount,
  });

  static Future<CacheSize> default_() =>
      RustLib.instance.api.crateApiCacheCacheSizeDefault();

  @override
  int get hashCode =>
      imageCacheBytes.hashCode ^
      imageCacheCount.hashCode ^
      webCacheCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CacheSize &&
          runtimeType == other.runtimeType &&
          imageCacheBytes == other.imageCacheBytes &&
          imageCacheCount == other.imageCacheCount &&
          webCacheCount == other.webCacheCount;
}
