// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `basename`, `build_download_filename`, `copy_file_with_progress`, `current_download_concurrency`, `download_author_avatar`, `download_cover`, `download_semaphore`, `map_record`, `progress_sender`, `resolve_download_path`, `resolve_under_data_dir`, `resume_queued_downloads`, `run_download`, `sanitize_filename`, `spawn_download`, `task_controls`, `uniquify_path`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DownloadControl`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`

/// 添加下载任务
Future<ApiDownloadTask> addDownload({
  required String videoId,
  required String title,
  required String coverUrl,
  required String quality,
  String? description,
  required List<String> tags,
}) => RustLib.instance.api.crateApiDownloadAddDownload(
  videoId: videoId,
  title: title,
  coverUrl: coverUrl,
  quality: quality,
  description: description,
  tags: tags,
);

/// 获取所有下载任务
Future<List<ApiDownloadTask>> getAllDownloads() =>
    RustLib.instance.api.crateApiDownloadGetAllDownloads();

/// 获取指定状态的下载任务
Future<List<ApiDownloadTask>> getDownloadsByStatus({required String status}) =>
    RustLib.instance.api.crateApiDownloadGetDownloadsByStatus(status: status);

/// 暂停下载
Future<bool> pauseDownload({required String taskId}) =>
    RustLib.instance.api.crateApiDownloadPauseDownload(taskId: taskId);

/// 继续下载
Future<bool> resumeDownload({required String taskId}) =>
    RustLib.instance.api.crateApiDownloadResumeDownload(taskId: taskId);

/// 取消/删除下载
Future<bool> deleteDownload({
  required String taskId,
  required bool deleteFile,
}) => RustLib.instance.api.crateApiDownloadDeleteDownload(
  taskId: taskId,
  deleteFile: deleteFile,
);

/// 导出下载文件到指定目录（通过 StreamSink 发送进度）
///
/// - 仅导出已下载完成且存在本地文件的任务
/// - 文件名格式：`[{作者}]{标题}.{ext}`，非法字符替换为 `_`
Stream<ApiExportProgress> exportDownloadsToDir({
  required List<String> taskIds,
  required String destDir,
}) => RustLib.instance.api.crateApiDownloadExportDownloadsToDir(
  taskIds: taskIds,
  destDir: destDir,
);

/// 批量暂停下载
Future<bool> pauseAllDownloads() =>
    RustLib.instance.api.crateApiDownloadPauseAllDownloads();

/// 批量继续下载
Future<bool> resumeAllDownloads() =>
    RustLib.instance.api.crateApiDownloadResumeAllDownloads();

/// 监听下载进度更新
Stream<ApiDownloadTask> subscribeDownloadProgress() =>
    RustLib.instance.api.crateApiDownloadSubscribeDownloadProgress();

/// 获取已下载视频的本地播放路径
Future<String?> getLocalVideoPath({required String videoId}) =>
    RustLib.instance.api.crateApiDownloadGetLocalVideoPath(videoId: videoId);
