// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'models.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ApiResult`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// 应用设置
@freezed
sealed class ApiAppSettings with _$ApiAppSettings {
  const ApiAppSettings._();
  const factory ApiAppSettings({
    required String defaultQuality,
    required int downloadConcurrent,
    String? proxyUrl,
    required String themeMode,
    required String language,
  }) = _ApiAppSettings;
  static Future<ApiAppSettings> default_() =>
      RustLib.instance.api.crateApiModelsApiAppSettingsDefault();
}

/// 作者信息
@freezed
sealed class ApiAuthorInfo with _$ApiAuthorInfo {
  const factory ApiAuthorInfo({
    required String id,
    required String name,
    String? avatarUrl,
    required bool isSubscribed,
  }) = _ApiAuthorInfo;
}

/// Banner 信息
@freezed
sealed class ApiBanner with _$ApiBanner {
  const factory ApiBanner({
    required String title,
    String? description,
    required String picUrl,
    String? videoCode,
  }) = _ApiBanner;
}

/// Cloudflare 验证请求
@freezed
sealed class ApiCloudflareChallenge with _$ApiCloudflareChallenge {
  const factory ApiCloudflareChallenge({
    required String url,
    required String userAgent,
  }) = _ApiCloudflareChallenge;
}

/// 评论
@freezed
sealed class ApiComment with _$ApiComment {
  const factory ApiComment({
    required String id,
    required String userName,
    String? userAvatar,
    required String content,
    required String time,
    required int likes,
    required int dislikes,
    required List<ApiComment> replies,
    required bool hasMoreReplies,
  }) = _ApiComment;
}

/// 评论列表结果
@freezed
sealed class ApiCommentList with _$ApiCommentList {
  const factory ApiCommentList({
    required List<ApiComment> comments,
    required int total,
    required int page,
    required bool hasNext,
  }) = _ApiCommentList;
}

@freezed
sealed class ApiDownloadStatus with _$ApiDownloadStatus {
  const ApiDownloadStatus._();

  const factory ApiDownloadStatus.pending() = ApiDownloadStatus_Pending;
  const factory ApiDownloadStatus.downloading() = ApiDownloadStatus_Downloading;
  const factory ApiDownloadStatus.paused() = ApiDownloadStatus_Paused;
  const factory ApiDownloadStatus.completed() = ApiDownloadStatus_Completed;
  const factory ApiDownloadStatus.failed({required String error}) =
      ApiDownloadStatus_Failed;
}

/// 下载任务
@freezed
sealed class ApiDownloadTask with _$ApiDownloadTask {
  const factory ApiDownloadTask({
    required String id,
    required String videoId,
    required String title,
    required String coverUrl,
    String? coverPath,
    String? authorId,
    String? authorName,
    String? authorAvatarUrl,
    String? authorAvatarPath,
    required String quality,
    String? description,
    required List<String> tags,
    required ApiDownloadStatus status,
    required double progress,
    required BigInt downloadedBytes,
    required BigInt totalBytes,
    required BigInt speed,
    required PlatformInt64 createdAt,
    String? filePath,
  }) = _ApiDownloadTask;
}

/// 收藏/稀后观看列表结果
@freezed
sealed class ApiFavoriteList with _$ApiFavoriteList {
  const factory ApiFavoriteList({
    required List<ApiVideoCard> videos,
    required int total,
    required int page,
    required bool hasNext,
  }) = _ApiFavoriteList;
}

/// 单个过滤选项
@freezed
sealed class ApiFilterOption with _$ApiFilterOption {
  const factory ApiFilterOption({
    required String value,
    required String label,
  }) = _ApiFilterOption;
}

/// 过滤选项（从网页解析）
@freezed
sealed class ApiFilterOptions with _$ApiFilterOptions {
  const factory ApiFilterOptions({
    required List<ApiFilterOption> genres,
    required List<ApiTagGroup> tags,
    required List<ApiFilterOption> sorts,
    required List<ApiFilterOption> years,
    required List<ApiFilterOption> durations,
  }) = _ApiFilterOptions;
}

/// 首页数据
@freezed
sealed class ApiHomePage with _$ApiHomePage {
  const factory ApiHomePage({
    String? formToken,
    String? avatarUrl,
    String? username,
    ApiBanner? banner,
    required List<ApiVideoCard> latestRelease,
    required List<ApiVideoCard> latestUpload,
    required List<ApiHomeSection> sections,
  }) = _ApiHomePage;
}

/// 首页分区
@freezed
sealed class ApiHomeSection with _$ApiHomeSection {
  const factory ApiHomeSection({
    required String name,
    required List<ApiVideoCard> videos,
  }) = _ApiHomeSection;
}

/// 我的列表信息（收藏、稍后观看等）
@freezed
sealed class ApiMyListInfo with _$ApiMyListInfo {
  const factory ApiMyListInfo({
    required bool isWatchLater,
    required List<ApiMyListItem> items,
  }) = _ApiMyListInfo;
}

/// 我的列表项
@freezed
sealed class ApiMyListItem with _$ApiMyListItem {
  const factory ApiMyListItem({
    required String code,
    required String title,
    required bool isSelected,
  }) = _ApiMyListItem;
}

/// 播放历史记录
@freezed
sealed class ApiPlayHistory with _$ApiPlayHistory {
  const factory ApiPlayHistory({
    required String videoId,
    required String title,
    required String coverUrl,
    required double progress,
    required int duration,
    required PlatformInt64 lastPlayedAt,
  }) = _ApiPlayHistory;
}

/// 播放历史列表
@freezed
sealed class ApiPlayHistoryList with _$ApiPlayHistoryList {
  const factory ApiPlayHistoryList({
    required List<ApiPlayHistory> items,
    required int total,
    required int page,
    required bool hasNext,
  }) = _ApiPlayHistoryList;
}

/// 播放列表信息
@freezed
sealed class ApiPlaylistInfo with _$ApiPlaylistInfo {
  const factory ApiPlaylistInfo({
    String? name,
    required List<ApiVideoCard> videos,
  }) = _ApiPlaylistInfo;
}

/// 搜索过滤条件
@freezed
sealed class ApiSearchFilters with _$ApiSearchFilters {
  const ApiSearchFilters._();
  const factory ApiSearchFilters({
    String? query,
    String? genre,
    required List<String> tags,
    required bool broadMatch,
    String? sort,
    String? year,
    String? month,
    String? date,
    String? duration,
    required int page,
  }) = _ApiSearchFilters;
  static Future<ApiSearchFilters> default_() =>
      RustLib.instance.api.crateApiModelsApiSearchFiltersDefault();
}

/// 搜索结果
@freezed
sealed class ApiSearchResult with _$ApiSearchResult {
  const factory ApiSearchResult({
    required List<ApiVideoCard> videos,
    required int total,
    required int page,
    required bool hasNext,
  }) = _ApiSearchResult;
}

/// 系列信息
@freezed
sealed class ApiSeriesInfo with _$ApiSeriesInfo {
  const factory ApiSeriesInfo({
    required String id,
    required String title,
    required List<ApiSeriesVideo> videos,
    required int currentIndex,
  }) = _ApiSeriesInfo;
}

/// 系列中的单个视频
@freezed
sealed class ApiSeriesVideo with _$ApiSeriesVideo {
  const factory ApiSeriesVideo({
    required String id,
    required String title,
    required String coverUrl,
    required String episode,
  }) = _ApiSeriesVideo;
}

/// 我的订阅页数据
@freezed
sealed class ApiSubscriptionsPage with _$ApiSubscriptionsPage {
  const factory ApiSubscriptionsPage({
    required List<ApiAuthorInfo> authors,
    required List<ApiVideoCard> videos,
    required int page,
    required bool hasNext,
  }) = _ApiSubscriptionsPage;
}

/// 标签分组
@freezed
sealed class ApiTagGroup with _$ApiTagGroup {
  const factory ApiTagGroup({
    required String name,
    required List<ApiFilterOption> tags,
  }) = _ApiTagGroup;
}

/// 用户信息
@freezed
sealed class ApiUserInfo with _$ApiUserInfo {
  const factory ApiUserInfo({
    required String id,
    required String name,
    String? avatarUrl,
    required bool isLoggedIn,
  }) = _ApiUserInfo;
}

/// 视频卡片信息（列表展示用）
@freezed
sealed class ApiVideoCard with _$ApiVideoCard {
  const factory ApiVideoCard({
    required String id,
    required String title,
    required String coverUrl,
    String? duration,
    String? views,
    String? uploadDate,
    required List<String> tags,
  }) = _ApiVideoCard;
}

/// 视频详情信息
@freezed
sealed class ApiVideoDetail with _$ApiVideoDetail {
  const factory ApiVideoDetail({
    required String id,
    required String title,
    String? chineseTitle,
    required String coverUrl,
    String? description,
    String? duration,
    String? views,
    int? likePercent,
    int? dislikePercent,
    int? likesCount,
    int? dislikesCount,
    String? uploadDate,
    ApiAuthorInfo? author,
    required List<String> tags,
    required List<ApiVideoQuality> qualities,
    ApiSeriesInfo? series,
    required List<ApiVideoCard> relatedVideos,
    String? formToken,
    String? currentUserId,
    required bool isFav,
    int? favTimes,
    ApiPlaylistInfo? playlist,
    ApiMyListInfo? myList,
  }) = _ApiVideoDetail;
}

/// 视频清晰度
@freezed
sealed class ApiVideoQuality with _$ApiVideoQuality {
  const factory ApiVideoQuality({
    required String quality,
    required String url,
  }) = _ApiVideoQuality;
}
