// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_search_url`

/// 执行搜索 - 使用 10 分钟缓存
Future<ApiSearchResult> search({required ApiSearchFilters filters}) =>
    RustLib.instance.api.crateApiSearchSearch(filters: filters);

/// 获取过滤选项（从网页实际提取的数据）
Future<ApiFilterOptions> getFilterOptions() =>
    RustLib.instance.api.crateApiSearchGetFilterOptions();

/// 获取首页推荐（默认搜索结果）
Future<ApiSearchResult> getHomeVideos({required int page}) =>
    RustLib.instance.api.crateApiSearchGetHomeVideos(page: page);

/// 获取首页数据（包含各分区）- 使用 10 分钟缓存
Future<ApiHomePage> getHomepage() =>
    RustLib.instance.api.crateApiSearchGetHomepage();
