// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'settings.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `dir_size`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 获取应用设置
Future<ApiAppSettings> getSettings() =>
    RustLib.instance.api.crateApiSettingsGetSettings();

/// 保存应用设置
Future<bool> saveSettings({required ApiAppSettings settings}) =>
    RustLib.instance.api.crateApiSettingsSaveSettings(settings: settings);

/// 设置默认清晰度
Future<bool> setDefaultQuality({required String quality}) =>
    RustLib.instance.api.crateApiSettingsSetDefaultQuality(quality: quality);

/// 设置下载并发数
Future<bool> setDownloadConcurrent({required int count}) =>
    RustLib.instance.api.crateApiSettingsSetDownloadConcurrent(count: count);

/// 设置代理
Future<bool> setProxy({String? proxyUrl}) =>
    RustLib.instance.api.crateApiSettingsSetProxy(proxyUrl: proxyUrl);

/// Flutter 侧 settingsState 的持久化（JSON string）
Future<String?> getFlutterSettings() =>
    RustLib.instance.api.crateApiSettingsGetFlutterSettings();

/// Flutter 侧 settingsState 的持久化（JSON string）
Future<bool> saveFlutterSettings({required String json}) =>
    RustLib.instance.api.crateApiSettingsSaveFlutterSettings(json: json);

/// 通用 KV：读取 settings 表中的字符串值
Future<String?> getKv({required String key}) =>
    RustLib.instance.api.crateApiSettingsGetKv(key: key);

/// 通用 KV：写入 settings 表中的字符串值
Future<bool> setKv({required String key, required String value}) =>
    RustLib.instance.api.crateApiSettingsSetKv(key: key, value: value);

/// 通用 KV：删除 settings 表中的键
Future<bool> deleteKv({required String key}) =>
    RustLib.instance.api.crateApiSettingsDeleteKv(key: key);

/// 获取缓存大小
Future<CacheInfo> getCacheSize() =>
    RustLib.instance.api.crateApiSettingsGetCacheSize();

/// 获取数据目录路径（用于桌面端打开数据存储目录）
Future<String> getDataDirPath() =>
    RustLib.instance.api.crateApiSettingsGetDataDirPath();

/// 初始化应用（启动时调用）
Future<bool> initApp({required String dataDir, required String cacheDir}) =>
    RustLib.instance.api.crateApiSettingsInitApp(
      dataDir: dataDir,
      cacheDir: cacheDir,
    );

/// 获取应用版本信息
Future<String> getAppVersion() =>
    RustLib.instance.api.crateApiSettingsGetAppVersion();

/// 缓存信息
@freezed
sealed class CacheInfo with _$CacheInfo {
  const factory CacheInfo({
    required BigInt coverCacheSize,
    required BigInt videoCacheSize,
    required BigInt totalSize,
  }) = _CacheInfo;
}
