// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 获取当前用户信息
Future<ApiUserInfo?> getCurrentUser() =>
    RustLib.instance.api.crateApiUserGetCurrentUser();

/// 检查登录状态
Future<bool> isLoggedIn() => RustLib.instance.api.crateApiUserIsLoggedIn();

/// 登出
Future<bool> logout() => RustLib.instance.api.crateApiUserLogout();

/// 获取收藏列表 (喜欢的影片)
Future<ApiFavoriteList> getFavorites({required int page}) =>
    RustLib.instance.api.crateApiUserGetFavorites(page: page);

/// 获取我的列表
Future<ApiFavoriteList> getMyList({
  required String listType,
  required int page,
}) =>
    RustLib.instance.api.crateApiUserGetMyList(listType: listType, page: page);

/// 添加到收藏
Future<bool> addToFavorites({
  required String videoCode,
  required String formToken,
  required String xCsrfToken,
  required String userId,
}) => RustLib.instance.api.crateApiUserAddToFavorites(
  videoCode: videoCode,
  formToken: formToken,
  xCsrfToken: xCsrfToken,
  userId: userId,
);

/// 从收藏移除
Future<bool> removeFromFavorites({
  required String videoCode,
  required String formToken,
  required String xCsrfToken,
  required String userId,
}) => RustLib.instance.api.crateApiUserRemoveFromFavorites(
  videoCode: videoCode,
  formToken: formToken,
  xCsrfToken: xCsrfToken,
  userId: userId,
);

/// 从列表删除视频
Future<bool> deleteFromList({
  required String listType,
  required String videoCode,
  required String formToken,
  required String xCsrfToken,
}) => RustLib.instance.api.crateApiUserDeleteFromList(
  listType: listType,
  videoCode: videoCode,
  formToken: formToken,
  xCsrfToken: xCsrfToken,
);

/// 获取订阅作者列表
Future<List<ApiAuthorInfo>> getSubscribedAuthors({required int page}) =>
    RustLib.instance.api.crateApiUserGetSubscribedAuthors(page: page);

/// 获取我的订阅页（作者 + 订阅更新视频）
Future<ApiSubscriptionsPage> getMySubscriptions({required int page}) =>
    RustLib.instance.api.crateApiUserGetMySubscriptions(page: page);

/// 订阅作者
Future<bool> subscribeAuthor({
  required String artistId,
  required String userId,
  required String formToken,
  required String xCsrfToken,
}) => RustLib.instance.api.crateApiUserSubscribeAuthor(
  artistId: artistId,
  userId: userId,
  formToken: formToken,
  xCsrfToken: xCsrfToken,
);

/// 取消订阅作者
Future<bool> unsubscribeAuthor({
  required String artistId,
  required String userId,
  required String formToken,
  required String xCsrfToken,
}) => RustLib.instance.api.crateApiUserUnsubscribeAuthor(
  artistId: artistId,
  userId: userId,
  formToken: formToken,
  xCsrfToken: xCsrfToken,
);

/// 获取播放历史
Future<ApiPlayHistoryList> getPlayHistory({
  required int page,
  required int pageSize,
}) => RustLib.instance.api.crateApiUserGetPlayHistory(
  page: page,
  pageSize: pageSize,
);

/// 添加/更新播放历史
Future<bool> updatePlayHistory({
  required String videoId,
  required String title,
  required String coverUrl,
  required double progress,
  required int duration,
}) => RustLib.instance.api.crateApiUserUpdatePlayHistory(
  videoId: videoId,
  title: title,
  coverUrl: coverUrl,
  progress: progress,
  duration: duration,
);

/// 删除单条播放历史
Future<bool> deletePlayHistory({required String videoId}) =>
    RustLib.instance.api.crateApiUserDeletePlayHistory(videoId: videoId);

/// 清空播放历史
Future<bool> clearPlayHistory() =>
    RustLib.instance.api.crateApiUserClearPlayHistory();

/// 获取视频的播放进度
Future<ApiPlayHistory?> getVideoProgress({required String videoId}) =>
    RustLib.instance.api.crateApiUserGetVideoProgress(videoId: videoId);

/// 设置 Cookie（从 WebView 导入）
Future<bool> setCookies({required List<(String, String)> cookies}) =>
    RustLib.instance.api.crateApiUserSetCookies(cookies: cookies);

/// 设置 Cloudflare Cookie
Future<bool> setCfClearance({required String cookieValue}) =>
    RustLib.instance.api.crateApiUserSetCfClearance(cookieValue: cookieValue);

/// 获取需要 Cloudflare 验证时的 URL 和 User-Agent
Future<ApiCloudflareChallenge?> getCloudflareChallengeInfo() =>
    RustLib.instance.api.crateApiUserGetCloudflareChallengeInfo();

/// 获取登录页面的表单 `_token`
Future<String> getLoginFormToken() =>
    RustLib.instance.api.crateApiUserGetLoginFormToken();

/// 登录
Future<bool> login({
  required String email,
  required String password,
  required String formToken,
  required String xCsrfToken,
}) => RustLib.instance.api.crateApiUserLogin(
  email: email,
  password: password,
  formToken: formToken,
  xCsrfToken: xCsrfToken,
);
