// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 获取视频详情
Future<ApiVideoDetail> getVideoDetail({required String videoId}) =>
    RustLib.instance.api.crateApiVideoGetVideoDetail(videoId: videoId);

/// 获取视频评论
Future<ApiCommentList> getVideoComments({
  required String videoId,
  required int page,
}) => RustLib.instance.api.crateApiVideoGetVideoComments(
  videoId: videoId,
  page: page,
);

/// 获取评论的回复
Future<List<ApiComment>> getCommentReplies({required String commentId}) =>
    RustLib.instance.api.crateApiVideoGetCommentReplies(commentId: commentId);

/// 获取视频播放地址
Future<String> getVideoUrl({
  required String videoId,
  required String quality,
}) => RustLib.instance.api.crateApiVideoGetVideoUrl(
  videoId: videoId,
  quality: quality,
);

/// 添加视频到收藏
Future<bool> addToFavorites({required String videoId}) =>
    RustLib.instance.api.crateApiVideoAddToFavorites(videoId: videoId);

/// 从收藏移除视频
Future<bool> removeFromFavorites({required String videoId}) =>
    RustLib.instance.api.crateApiVideoRemoveFromFavorites(videoId: videoId);

/// 点赞评论
Future<bool> likeComment({required String commentId}) =>
    RustLib.instance.api.crateApiVideoLikeComment(commentId: commentId);

/// 发表评论
Future<ApiComment> postComment({
  required String videoId,
  required String content,
  String? replyTo,
}) => RustLib.instance.api.crateApiVideoPostComment(
  videoId: videoId,
  content: content,
  replyTo: replyTo,
);
